PR
femstuff/todo-app pull request #1
Opened 2024-08-30 09:36 UTC by femstuff

2024-08-30 14:38 UTC, dirtymew requested changes
Привет Тихон

теперь PR нормально оформлен - отлично

по решению дал комментарии что поправить и улучшить

другие задания со звездочкой будешь делать?

2024-08-30 14:38 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.22 AS builder
go 1.22.5 в go mod - лучше сразу взять образ с нужной версией go

2024-08-30 14:38 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=1 GOOS=linux go build -o /taskapp
CGO_ENABLED=1 GOOS=linux это лучше в ENV обьявить

2024-08-30 14:38 UTC, dirtymew commented on Dockerfile
> +FROM ubuntu
тут рекомендовал бы взять образ полегче - alpine например

2024-08-30 14:38 UTC, dirtymew commented on Dockerfile
> +COPY --from=builder . .
хмм а смысл тогда этапа билдера? 

возьми только фронт и бинарник собранный оттуда - зачем все копировать...

2024-08-30 14:38 UTC, dirtymew commented on handlers.go
> +func getTaskHandler(db *sql.DB) http.HandlerFunc {
тут не совсем верно работаешь с зависимостями

ты передаешь db и потом каждый раз инициализируешь storage в каждом запросе - это неверно

можно передать зависимостью storage тогда и инициализировать его  один раз  при старте

2024-08-30 14:38 UTC, dirtymew commented on handlers.go
> +		w.Write([]byte(`{}`))
_ , _ = w.Write(resp)
тут стоит либо явно проигнорировать ошибку или ее логировать
хорошие линтеры на это ругаться будут и не зря

2024-08-30 14:38 UTC, dirtymew commented on handlers.go
> +func addTaskHandler(db *sql.DB) http.HandlerFunc {
хендлеры перегружены проверками - рекомендовал бы порефакторить и вынести в функции и пакеты

2024-08-30 14:38 UTC, dirtymew commented on handlers.go
> +import (
в целом рекомендации по структуре проекта

- проект не маленький и уже имеет абстракции которые хорошо бы на пакеты разделить 
- по сруктуре см https://github.com/golang-standards/project-layout
- по архитектуре https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10
- еще по архитектуре посмотри на задание про посылки там было 2 уровня service и storage... тут по хорошему  еще должен быть уровень api/transport

это все рекомендации - они немного за рамками курса, если пока не понятно то необязательно так делать

2024-08-30 14:38 UTC, dirtymew commented on tasks.go
> +type TaskResponse struct {
это я бы определял не тут а там где другая структура для ответа - см коммент ниже

2024-08-30 14:38 UTC, dirtymew commented on tasks.go
> +func (s SchedulerStore) GetTasks() (TaskResponse, error) {
TaskResponse я бы возвращал бы []Task - так получилось некоторое связывание слоев - мы как бы знаем как результат используется дальше

по идее storage должен быть независимым компонентом

2024-08-30 14:38 UTC, dirtymew commented on tasks.go
> +		sql.Named("limit", 50))
лимит в константу стоит вынести

2024-08-30 14:38 UTC, dirtymew commented on tasks.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-08-30 14:38 UTC, dirtymew commented on handlers.go
> +		task, err := store.Get(id)
тут ты 2 запросы делаешь - не оптимально

можно просто сделать сразу запрос к storage delete а он пусть вернет ошибку 

в update тоже самое

2024-08-30 14:38 UTC, dirtymew commented on tasks.go
> +	if err != nil {
тут можно проверить RowsAffected - и вернуть ошибку если запрос не был применен ни к одной строке

2024-08-30 14:38 UTC, dirtymew commented on tasks.go
> +	if err != nil {
в update тоже самое

2024-08-30 14:38 UTC, dirtymew commented on tasks.go
> +	row := s.db.QueryRow("SELECT * FROM scheduler WHERE id = :id",
лучше явно указывать поля а не *

2024-08-30 14:38 UTC, dirtymew commented on main.go
> +	if err = http.ListenAndServe(":"+strconv.Itoa(ServPort), router); err != nil {
еще бы перед стартом написать лог на каком порту запустилось приложение

будет отлично

2024-08-30 14:38 UTC, dirtymew commented on main.go
> +	"github.com/go-chi/chi"
импорты должны быть сгруппированны на 2-3 группы

используй go imports или настройки ide

2024-08-30 14:38 UTC, dirtymew commented on utility.go
> +package main
utility/tools/helpers - считаются плохой практикой 

лучше разнести функции по соответвующим файлам или пакетам

2024-08-30 14:38 UTC, dirtymew commented on README.md
> +Перейти к самому вебприложению -  http://localhost:7540/
неплохо бы описать какие задания со * выполенены
и как запустить тесты + добавить в тестах в settings.go необходимые опции для тестирования

2024-08-30 14:38 UTC, dirtymew commented on handlers.go
> +func updateTaskHandler(db *sql.DB) http.HandlerFunc {
Падают тесты - должны обязательно проходить

2024-09-08 04:59 UTC, femstuff commented
Антон, привет, другие задания  со * постараюсь сделать в срок. Пока работаю по ПР, мало времени.

2024-09-08 12:02 UTC, dirtymew approved these changes
Привет Тихон

задание принято

поздравляю и желаю удачи

2024-09-09 05:12 UTC, merged